services:
  iwf:
    image: iworkflowio/iwf-server-lite:latest
    environment:
      - AUTO_FIX_WORKER_URL=mycode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:8801:8801 
      - 127.0.0.1:7233:7233 
      - 127.0.0.1:8233:8233
    # volumes: 
    #   - ./dc/start-lite-server.sh:/iwf/lite/start-lite-server.sh
  mycode:
    build: 
      dockerfile: ./Dockerfile
    # volumes:
    #   - ./:/usr/src/myapp
    ports:
      - 127.0.0.1:8080:8080 
      - 127.0.0.1:8803:8803 
    expose:
      - 8803
    develop:
      watch: 
        - path: ./src/main/
          action: sync+restart
          target: /usr/src/myapp/src/main/
  # frontend:
  #   image: nginx
  #   ports:
  #     - 127.0.0.1:8090:80
  #   volumes:
  #     - ./js/:/usr/share/nginx/html/js
